spring.application.name=adaptive-mfa-backend

# Cấu hình Reverse Proxy
server.forward-headers-strategy=framework

# Cấu hình kết nối MySQL (Tự động đọc biến môi trường từ Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/adaptive_mfa_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}

# Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cấu hình JWT Key
app.jwt.secret=AdaptiveMFA_Secret_Key_For_Security_Token_Generation_2026_Project
webauthn.relying-party.id=localhost
webauthn.origin=http://localhost:8080
server.port=${PORT:8080}